### ISSUE TITLE
Add "/trop run backport-to $branchname"

### ISSUE THREAD

**Issue by ckerr** [codebytere/trop#19]
For when you have a one-off need and don't want to pollute the label namespace.

Inspired by a joking suggestion that I made to @MarshallOfSound last night that we fix
`electron/set-appropriate-defaults-for-webview-options` and
`electron/set-appropriate-defaults-for-webview-options_1-8-x`
with a meta-PR that had the label 
`target/set-appropriate-defaults-for-webview-options_1-8-x`

### TODO

- [x] get feedback from @codebytere and @MarshallOfSound
- [x] move user authentication logic to outside of `/trop run backport` command handler
- [x] add code to recognize `/trop run backport-to branch $branchname` to pull out the branchname
- [x] change backport/utils:
   - [x] two forms of backportPR, one taking a label and the other a branchname
   - [x] if no label is provided, don't try to remove it
   - [x] if a branch is provided, don't try to guess the branchname from the label
- [x] change src/index.js:
   - [x] add a sibling func next to `backportAllLabels()` called `backportTo(branchname)` that prepares `context` and passes the work along to `utils`
   - [ ] finish the work in `robot.on('issue_comment.created')` to call `backportTo()`
- [x] tests

**Comment by codebytere** [comment]
Added in https://github.com/codebytere/trop/pull/20 😁
